### ISSUE TITLE
[JOSS Review] Installation

### ISSUE THREAD

**Issue by mbarzegary** [Sarc-Graph/sarcgraph#3]
Dear authors,

The software installation routine is straightforward, and there is no special issue with it. But, the general procedure was a bit weird to me. The user needs to clone the repository just for the YAML configuration file and the tutorials, and although the repository contains the source code of the software, it gets installed from PyPI online repositories. This way eliminates the possibility of installing a developer version of the tool (like for performing modification and customization to the core functionalities, the possibility of which is highlighted in the paper). Moreover, it makes the test procedure redundant because the pytest routines check the codes in the `sarcgraph` directory, but the software gets installed from another source (an online repository). You may consider adding a standard installation routine such that users can install the tool from the cloned local repository by executing `pip install -e .`.  It seems that the file `setup.py` is already there, but I’m not sure if it is functional for a local installation.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5322

**Comment by saeedmhz** [comment]
Thank you for your insightful comments regarding the installation process of our software. We appreciate your suggestions and have made the following changes to address your concerns:

To simplify the installation process, we have uploaded our package to the conda servers, including all dependencies. This allows users to create a new environment and install everything with just one command.

We have made our tutorial files accessible on Binder, enabling users to run them without the need to set up local environments. In addition, we have provided more in-depth instructions on how to download notebooks with and without cloning the repository.

We have updated the package on PyPI servers to include all dependencies except for FFmpeg, streamlining the pip installation process for users who prefer not to use conda.

We have added a separate section for developers in the documentation, which includes instructions for an editable install using the ``pip install -e .`` command with the ``setup.py`` file in the repository. This allows developers to install a local version of the tool for modifications and customizations.

Finally, we have revised the installation instructions on the GitHub README to match the updated documentation.

We believe that these changes will improve the user experience during the installation process and make it easier for users and developers to work with our software. We hope our revisions adequately address your concerns.

Please let us know if there are any further comments or suggestions.
