### ISSUE TITLE
JOSS Review - Needs statement of need

### ISSUE THREAD

**Issue by kenatcampbellmusclelab** [Sarc-Graph/sarcgraph#8]
Paper needs a clear statement of need

Reference to https://github.com/openjournals/joss-reviews/issues/5322#issuecomment-1530387975

**Comment by saeedmhz** [comment]
Thank you for your comment regarding the need for a clear "Statement of Need" in our paper. We appreciate the opportunity to address this concern.

We have added a "Statement of Need" section to our manuscript. This new section comprehensively discusses the challenges of the field and the target user group, ensuring that our paper adheres to the JOSS guidelines.
